name: ci
run-name: ci (${{ github.event_name }})
on:
  pull_request:
  workflow_call:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  base_ref: ${{ github.base_ref || 'main' }}
jobs:
  pre-commit:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-slim, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
      - id: get-start-ref
        run: |
          set -x
          base_branch=${{ toJSON(env.base_ref) }}
          this_branch="$(git branch --show-current)"
          if [[ -z "$this_branch" ]]; then
            this_branch=${{ toJSON(github.head_ref) }}
          fi
          git fetch origin "$base_branch" --depth=1
          if git merge-base --is-ancestor origin/"$base_branch" HEAD; then
            # literraly one commit ahead of the base
            true
          else
            # fetch our branch's history up to the base
            git fetch origin "$this_branch" --shallow-exclude="$base_branch"
            # make sure we have the common ancestor
            git fetch origin "$this_branch" --deepen=1
          fi
          if git merge-base --is-ancestor origin/"$base_branch" HEAD; then
            # base is in our history, i.e. base has not advanced past us
            true
          else
            # base is not in our history, i.e. base has advanced past us
            # fetch the base branch history up to our branch
            git fetch origin "$base_branch" --shallow-exclude="$this_branch"
            # fetch the common ancestor
            git fetch origin "$base_branch" --deepen=1
          fi
          start_ref="$(git merge-base origin/"$base_branch" HEAD)"
          echo "start_ref=$start_ref" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c #v6
        with:
          go-version: ${{ matrix.go }}
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 #v4
        with:
          install: true
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ runner.arch }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: |
          export SKIP=no-commit-to-branch
          pre-commit run \
            --from-ref ${{ toJSON(steps.get-start-ref.outputs.start_ref) }} \
            --to-ref HEAD \
            --show-diff-on-failure
  test-and-report:
    uses: ./.github/workflows/test-and-report.yaml
